[package]
name = "piscem"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
cmake = "0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"


[profile.release]
lto = "thin"
opt-level = 3
